services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'test_db'
      MYSQL_ROOT_PASSWORD: 'rootuser'
      MYSQL_USER: 'defaultuser'
      MYSQL_PASSWORD: 'defaultpwd'
    ports:
      - '3306:3306'
    volumes:
      - './.mysql-data:/var/lib/mysql'

  azure-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    command: "azurite-blob --blobHost 0.0.0.0 --blobPort 10000 --skipApiVersionCheck"
    ports:
      - "10000:10000"
    volumes:
      - storage_data:/data

volumes:
  storage_data:
