app:
  version: 1.0

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always

spring:
  application:
    name: rag
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      physical_naming_strategy: io.hypersistence.utils.hibernate.naming.CamelCaseToSnakeCaseNamingStrategy
      ddl-auto: ${DB_DDL_AUTO:validate}
    show-sql: 'true'
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:test_db}
    username: ${DB_USERNAME:defaultuser}
    password: ${DB_PASSWORD:defaultpwd}
    driver-class-name=com: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_AUTH_CLIENT_ID:}
            clientSecret: ${GOOGLE_AUTH_CLIENT_SECRET:}
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 10000
            readTimeout: 10000
            loggerLevel: headers
          question:
            url: ${QUESTION_SERVICE_URL:http://localhost:8100}
    azure:
      storage:
        blob:
          connection-string: ${AZURE_BLOB_STORAGE_CONNECTION_STRING:}
          endpoint: ${AZURE_BLOB_STORAGE_ENDPOINT:}
          url: ${AZURE_BLOB_STORAGE_ENDPOINT:}/${BLOB_NAME:documents}/

springdoc:
  swagger-ui:
    path: ${SWAGGER_PATH:/swagger}
    enabled: ${ENABLE_SWAGGER:true}

logging:
  send-trace: ${EXCEPTION_HANDLER_SEND_TRACE:true}
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
      estudos:
        rag: DEBUG

debug: true
